name: Deploy to EC2 on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH for EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY_BASE64 }}" > test1.pem
          chmod 600 test1.pem
          ssh-keyscan -H 3.228.66.243 >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add test1.pem

      - name: Deploy to EC2
        run: |
          ssh -i test1.pem ubuntu@3.228.66.243 << 'EOF'
            # Navigate to project or clone if not existing
            cd /home/ubuntu/SkillForge-Backend || git clone git@github.com:nvp18/SkillForge-Backend.git /home/ubuntu/SkillForge-Backend
            cd /home/ubuntu/SkillForge-Backend

            # Pull latest code and restart backend service
            git pull origin main
            mvn spring-boot:stop || echo "Service not running"
            mvn clean install
            mvn spring-boot:run
          EOF