name: Deploy to EC2 on Push to Main

on:
  push:
    branches:
      - main  # Trigger the workflow on any push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH for EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY_BASE64 }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@3.228.66.243 << 'EOF'
            # Navigate to the project directory or clone if it doesn't exist
            cd /home/ec2-user/SkillForge-Backend || git clone git@github.com:nvp18/SkillForge-Backend.git /home/ec2-user/SkillForge-Backend
            cd /home/ec2-user/SkillForge-Backend

            # Pull the latest changes
            git pull origin main

            # Stop and restart your backend service
            mvn spring-boot:stop || echo "Service not running, skipping stop"
            mvn clean install
            mvn spring-boot:run
          EOF
